### PR TITLE
Package Import Improvements for Pyfuntofem

### PR DESCRIPTION
**Pull request by sean-engelstad**
Improvements in python pyfuntofem python package
- Cleaned up and simplified file structure in pyfuntofem using subdirectories driver, model, interface, optimization
- Interface subfolders interface/_tacs, interface/_fun3d have underscores in front to prevent import conflicts with the associated packages fun3d, tacs, etc.
- pyfuntofem package imports all available classes and methods in the package now for much easier importing
     import pyfuntofem OR from pyfuntofem import * OR subfolder imports like from pyfuntofem.driver import *
- Interface modules for fun3d, su2, tacs, etc. only imported if the associated package fun3d, tacs, pysu2 is available (checked using importlib)

Updated Import Statements in funtofem
- Updated unsteady example imports: diamond_unsteady and simple_sst
- Updated unit test imports: all relevant files in tests/

### CODE REVIEW

**Comment by sean-engelstad** [comment]
Note that the unit tests did not run here, but I tested them using testflo and all of them passed except the test_transfer_scheme MPI one because I was running on serial.

**Comment by sean-engelstad** [comment]
Also, I think I'm still missing one or two __all__ headers in the pyfuntofem source code

**Comment by gjkennedy** [comment]
I like the clean up. The import statements look nicer now. 

Q: Why does each interface have to live in its own separate subdirectory though? That will get a bit awkward for code dev/navigating.

**Comment by sean-engelstad** [comment]
I put each of the interfaces in their own subfolder _fun3d, _tacs, etc., so that I could check that the associated packages are available before importing. However, I don't have to do it that way. I'll change it so that all of the interfaces are in the same folder and just do the importlib checks for each interface package in the interface/__init__.py file.

**Comment by sean-engelstad** [comment]
- I've now finished simplifying the interface folder so that there are not two levels of subfolders, now it is only pyfuntofem/interface/*.py.
- The unit tests all pass with new import statements
- The importlib appropriately checks whether the available python packages are available such as fun3d, openmdao, tacs, pysu2 before importing associated interfaces or drivers to ensure the total pyfuntofem package is stable.
- Can do import directly from pyfuntofem now or just use subfolders as before.
   i) import pyfuntofem, then pyfuntofem.Variable, pyfuntofem.Fun3dInterface, etc.
   ii) from pyfuntofem import *; then Variable, Fun3dInterface, TacsSteadyInterface, etc. are the classes
   iii) from pyfuntofem.interface import * OR from pyfuntofem.interface import TacsSteadyInterface, Fun3dInterface, etc.

**Comment by sean-engelstad** [comment]
Also I split the TacsSteadyAnalysisDriver and TacsSteadyShapeDriver into two files now: tacs_driver.py and tacs_shape_driver.py respectively.

**Comment by rnpatel3** [comment]
Could you also fix the import statements in the other examples which were, I believe, functioning prior to this change i.e. piston theory, SU2/steady, cart3d/crm?

**Review by bburke38 — APPROVED** [review]
I'm going to merge this pull request so it's on a shared branch, but I'm not pushing it to master yet.

**Pull request merged**
