### PR TITLE
TACS Unsteady Interface

### PR DESCRIPTION
**Pull request by rnpatel3**
Work on the TACS unsteady interface

-  Utilizing the pyTACS API to load geometry from BDF files
- Forward aeroelastic interaction tested and notionally functional (aerothermoelastic capability tentatively included, not tested, not reflecting new heat flux calcs)
- Adjoint iterations for aeroelastic analysis run without code error, but issues with residual convergence

Example cases

- Diamond wing: Poor structural mesh leads to non-convergence of structural residuals in fwd analysis
- SimpleSST: Mesh works well for forward analysis, namelists provided to run gust simulation and store structural response

### CODE REVIEW

**Review by sean-engelstad — COMMENTED** [review]
I would like to change the two example cases to use callback=None and thus the default funtofem callback now. But other than that everything looks really good. The only places that could potentially change something for the steady case is tacs interface iterate() function which contains time_step= inputs now. However, Rohan and I went through that code and it shouldn't change the steady case.

**Comment by bburke38** [comment]
> I would like to change the two example cases to use callback=None and thus the default funtofem callback now. But other than that everything looks really good. The only places that could potentially change something for the steady case is tacs interface iterate() function which contains time_step= inputs now. However, Rohan and I went through that code and it shouldn't change the steady case.

Can you make the changes regarding the callback before we merge?

**Review by bburke38 — CHANGES_REQUESTED** [review]
Why is there a tacs_interface_unsteady_v2? Should this just replace an earlier tacs_interface_unsteady?

**Review by bburke38 — APPROVED** [review]

**Review by bburke38 — APPROVED** [review]
Looks good. There is an assertion in the body class to check if the analysis_type is recognized, I think this is redundant since there is already a method implemented to verify the analysis type that is called during initialize_transfer. But it shouldn't hurt anything for now--should modify in the future to be consistent.

**Pull request merged**
